language: java

jdk: openjdk8

sudo: required
services:
  - docker

env:
  DOCKER_APP: todo-list
  HEROKU_APP_NAME: ontodolist

script: 
  - mvn clean package
  - docker build -t $DOCKER_APP .

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker tag $DOCKER_APP $DOCKER_USER/$DOCKER_APP:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USER/$DOCKER_APP:$TRAVIS_BUILD_NUMBER
  - docker tag $DOCKER_APP $DOCKER_USER/$DOCKER_APP:latest
  - docker push $DOCKER_USER/$DOCKER_APP:latest
  
deploy:
 provider: heroku
 api-key: 
  secure: $HEROKU_APP_KEY
 app: $HEROKU_APP_NAME

 before_install:
  - chmod +x mvnw